package com.proofstamp.app.capture

import android.graphics.Bitmap
import java.security.MessageDigest
import kotlin.math.abs
import kotlin.math.sqrt
import kotlin.random.Random

/**
 * Invisible forensic watermark: a spread-spectrum luminance modulation keyed by
 * the photo's ID. Each 8x8 block is nudged ±AMPLITUDE luma by a pseudo-random
 * pattern derived from `sha256(photoId)` — invisible to the eye but detectable
 * in a recompressed/screenshot derivative even after the C2PA manifest is gone.
 *
 * Detection is a correlation score against the expected pattern for a given
 * photoId; it answers "was this generated by ProfStamp as <id>?", not "is this
 * AI". Not a replacement for the C2PA signature — a second, resilient layer.
 */
object WatermarkCodec {
    private const val BLOCK = 8
    private const val AMPLITUDE = 3
    /** Correlation threshold tuned so random images score ~±0.05 and marked ones >0.3. */
    const val DETECT_THRESHOLD = 0.18

    /** Invisibly modulates [bitmap]'s pixels with the pattern for [photoId]. */
    fun embed(bitmap: Bitmap, photoId: String) {
        val pattern = pattern(bitmap.width, bitmap.height, photoId)
        val w = bitmap.width
        val h = bitmap.height
        val px = IntArray(w * h)
        bitmap.getPixels(px, 0, w, 0, 0, w, h)
        for (y in 0 until h step BLOCK) {
            val pj = y / BLOCK
            if (pj >= pattern.size) break
            for (x in 0 until w step BLOCK) {
                val pi = x / BLOCK
                if (pi >= pattern[pj].size) break
                val d = pattern[pj][pi] * AMPLITUDE
                for (by in y until minOf(y + BLOCK, h)) {
                    val row = by * w
                    for (bx in x until minOf(x + BLOCK, w)) {
                        px[row + bx] = add(px[row + bx], d)
                    }
                }
            }
        }
        bitmap.setPixels(px, 0, w, 0, 0, w, h)
    }

    /**
     * Correlation between the image's per-block luma and the pattern for
     * [photoId]. ≥ [DETECT_THRESHOLD] ⇒ the mark is present.
     */
    fun detect(bitmap: Bitmap, photoId: String): Float {
        // Evaluate on a downscaled copy — cheap and more robust to re-encode noise.
        val sw = bitmap.width.coerceAtMost(1024)
        val sh = (bitmap.height.toLong() * sw / bitmap.width).toInt().coerceAtLeast(BLOCK * 2)
        val small = if (sw == bitmap.width) bitmap else Bitmap.createScaledBitmap(bitmap, sw, sh, true)
        val w = small.width
        val h = small.height
        val bx = w / BLOCK
        val by = h / BLOCK
        if (bx < 8 || by < 8) return 0f
        val pattern = pattern(w, h, photoId)

        val px = IntArray(w * h)
        small.getPixels(px, 0, w, 0, 0, w, h)
        // Per-block mean luma.
        val means = DoubleArray(bx * by)
        for (j in 0 until by) {
            for (i in 0 until bx) {
                var acc = 0.0
                var n = 0
                for (y in j * BLOCK until j * BLOCK + BLOCK) {
                    val row = y * w
                    for (x in i * BLOCK until i * BLOCK + BLOCK) {
                        val c = px[row + x]
                        acc += 0.299 * (c shr 16 and 0xFF) + 0.587 * (c shr 8 and 0xFF) + 0.114 * (c and 0xFF)
                        n++
                    }
                }
                means[j * bx + i] = acc / n
            }
        }
        // Zero-mean both sides; correlation with the ±1 pattern.
        var mp = 0.0
        var mm = 0.0
        for (v in means) mm += v
        mm /= means.size
        var num = 0.0
        var dp = 0.0
        var dm = 0.0
        for (j in 0 until by) for (i in 0 until bx) {
            val p = pattern[j][i].toDouble()
            val m = means[j * bx + i] - mm
            num += p * m
            dp += p * p
            dm += m * m
        }
        if (small !== bitmap && !small.isRecycled) small.recycle()
        if (dm == 0.0) return 0f
        return (num / sqrt(dp * dm)).toFloat()
    }

    /** Deterministic ±1 block pattern derived from sha256(seed). */
    private fun pattern(w: Int, h: Int, seed: String): Array<ByteArray> {
        val digest = MessageDigest.getInstance("SHA-256").digest(seed.toByteArray())
        val rng = Random(digest.fold(0L) { a, b -> (a shl 8) or (b.toLong() and 0xFF) })
        // Partial edge blocks get a pattern entry too — the embedder walks them.
        val bx = (w + BLOCK - 1) / BLOCK
        val by = (h + BLOCK - 1) / BLOCK
        return Array(by) { ByteArray(bx) { if (rng.nextBoolean()) 1 else -1 } }
    }

    private fun add(color: Int, d: Int): Int {
        val a = color ushr 24
        val r = ((color shr 16 and 0xFF) + d).coerceIn(0, 255)
        val g = ((color shr 8 and 0xFF) + d).coerceIn(0, 255)
        val b = ((color and 0xFF) + d).coerceIn(0, 255)
        return (a.toInt() shl 24) or (r shl 16) or (g shl 8) or b
    }
}
