package com.proofstamp.app.capture

import android.graphics.Bitmap
import java.security.MessageDigest
import kotlin.math.sqrt
import kotlin.random.Random

/**
 * Invisible forensic watermark: a spread-spectrum luminance modulation keyed by
 * the photo's ID. The image is divided into a fixed logical grid (CELLS_X across,
 * aspect-derived height) and each cell is nudged ±AMPLITUDE luma by a keyed
 * pseudo-random pattern derived from `sha256(photoId)` — invisible to the eye but
 * detectable in a recompressed/resized derivative even after the C2PA manifest
 * is gone. Being relative to image dimensions, the grid survives rescaling.
 *
 * Detection high-passes both the measured cell means and the expected pattern
 * (value minus 4-neighbor average) before correlating — this removes DC and
 * smooth photographic gradients that would otherwise swamp a ±AMPLITUDE mark.
 * It answers "was this generated by ProfStamp as <id>?", not "is this AI". Not a
 * replacement for the C2PA signature — a second, resilient layer.
 */
object WatermarkCodec {
    private const val CELLS_X = 48
    private const val AMPLITUDE = 8
    /** Correlation threshold on the high-passed signal; random images score <0.1. */
    const val DETECT_THRESHOLD = 0.25

    /** Invisibly modulates [bitmap]'s pixels with the pattern for [photoId]. */
    fun embed(bitmap: Bitmap, photoId: String) {
        val w = bitmap.width
        val h = bitmap.height
        val bx = CELLS_X
        val by = cellsY(w, h)
        val pattern = pattern(bx, by, photoId)
        val px = IntArray(w * h)
        bitmap.getPixels(px, 0, w, 0, 0, w, h)
        for (cj in 0 until by) {
            val y0 = cj * h / by
            val y1 = (cj + 1) * h / by
            for (ci in 0 until bx) {
                val x0 = ci * w / bx
                val x1 = (ci + 1) * w / bx
                val d = pattern[cj][ci] * AMPLITUDE
                for (y in y0 until y1) {
                    val row = y * w
                    for (x in x0 until x1) {
                        px[row + x] = add(px[row + x], d)
                    }
                }
            }
        }
        bitmap.setPixels(px, 0, w, 0, 0, w, h)
    }

    /**
     * High-pass correlation between the image's per-cell luma and the pattern for
     * [photoId]. ≥ [DETECT_THRESHOLD] ⇒ the mark is present.
     */
    fun detect(bitmap: Bitmap, photoId: String): Float {
        // Downscale for speed — the grid is relative, so cell indices are unchanged.
        val sw = bitmap.width.coerceAtMost(1024)
        val sh = (bitmap.height.toLong() * sw / bitmap.width).toInt().coerceAtLeast(8)
        val small = if (sw == bitmap.width) bitmap else Bitmap.createScaledBitmap(bitmap, sw, sh, true)
        val w = small.width
        val h = small.height
        val bx = CELLS_X
        val by = cellsY(w, h)
        val pattern = pattern(bx, by, photoId)

        val px = IntArray(w * h)
        small.getPixels(px, 0, w, 0, 0, w, h)
        // Per-cell mean luma.
        val means = DoubleArray(bx * by)
        for (cj in 0 until by) {
            val y0 = cj * h / by
            val y1 = (cj + 1) * h / by
            for (ci in 0 until bx) {
                val x0 = ci * w / bx
                val x1 = (ci + 1) * w / bx
                var acc = 0.0
                var n = 0
                for (y in y0 until y1) {
                    val row = y * w
                    for (x in x0 until x1) {
                        val c = px[row + x]
                        acc += 0.299 * (c shr 16 and 0xFF) + 0.587 * (c shr 8 and 0xFF) + 0.114 * (c and 0xFF)
                        n++
                    }
                }
                means[cj * bx + ci] = acc / n
            }
        }
        // High-pass both sides: value minus 4-neighbor mean, interior cells only.
        // Embedding shifts a cell's mean by d, so its high-passed value shifts by
        // d·(1 + 1/4·Σ pattern alignment) — correlating against the same transform
        // of the pattern keeps the response aligned while rejecting scene texture.
        var num = 0.0
        var dp = 0.0
        var dm = 0.0
        for (j in 1 until by - 1) {
            for (i in 1 until bx - 1) {
                val m = means[j * bx + i] -
                    (means[j * bx + i - 1] + means[j * bx + i + 1] +
                        means[(j - 1) * bx + i] + means[(j + 1) * bx + i]) / 4.0
                val p = pattern[j][i].toDouble() -
                    (pattern[j][i - 1] + pattern[j][i + 1] + pattern[j - 1][i] + pattern[j + 1][i]) / 4.0
                num += p * m
                dp += p * p
                dm += m * m
            }
        }
        if (small !== bitmap && !small.isRecycled) small.recycle()
        if (dm == 0.0 || dp == 0.0) return 0f
        return (num / sqrt(dp * dm)).toFloat()
    }

    private fun cellsY(w: Int, h: Int): Int =
        (CELLS_X.toLong() * h / w).toInt().coerceAtLeast(8)

    /** Deterministic ±1 cell pattern derived from sha256(seed). Fixed-size, image-relative. */
    private fun pattern(bx: Int, by: Int, seed: String): Array<ByteArray> {
        val digest = MessageDigest.getInstance("SHA-256").digest(seed.toByteArray())
        val rng = Random(digest.fold(0L) { a, b -> (a shl 8) or (b.toLong() and 0xFF) })
        return Array(by) { ByteArray(bx) { if (rng.nextBoolean()) 1 else -1 } }
    }

    private fun add(color: Int, d: Int): Int {
        val a = color ushr 24
        val r = ((color shr 16 and 0xFF) + d).coerceIn(0, 255)
        val g = ((color shr 8 and 0xFF) + d).coerceIn(0, 255)
        val b = ((color and 0xFF) + d).coerceIn(0, 255)
        return (a.toInt() shl 24) or (r shl 16) or (g shl 8) or b
    }
}
